version: '3'

services:
  prejournal:
    build:
      context: https://github.com/pondersource/prejournal.git#testsuite
      dockerfile: Dockerfile
    ports:
      - 8280:80
    hostname: prejournal.local
    expose:
      - 8280
    depends_on:
      - prejournal-db
  prejournal-db:
    build:
      context: https://github.com/pondersource/prejournal.git#testsuite
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prejournal_test # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 123456 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: prejournal_test # The PostgreSQL default database (automatically created at first launch)
  tikiwiki:
    build:
      context: .
      dockerfile: Dockerfile-tikiwiki
    ports:
      - 8180:80
    expose:
      - 8180
    depends_on:
      - tikiwiki-db
    hostname: tikiwiki.local
    environment:
      - TIKI_DB_HOST=tikiwiki-db
      - TIKI_DB_USER=tiki
      - TIKI_DB_PASS=wiki
      - TIKI_DB_NAME=tikiwiki
  tikiwiki-db:
    image: mariadb
    environment:
      - MYSQL_USER=tiki
      - MYSQL_PASSWORD=wiki
      - MYSQL_DATABASE=tikiwiki
      - MYSQL_ROOT_PASSWORD=tkwkiiii
  timeld-gateway:
    build:
      context: .
      dockerfile: Dockerfile-timeld-gateway
    environment:
      LOG_LEVEL: DEBUG
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # To accept the self-signed cert on the proxy;
      TIMELD_GATEWAY_GATEWAY: timeld-gateway.local
      TIMELD_GATEWAY_GENESIS: "true"
      TIMELD_GATEWAY_AUTH__KEY: test-timeld.rootkey:123456789abcdefghijk
      TIMELD_GATEWAY_SMTP__HOST: mailhog.local
      TIMELD_GATEWAY_SMTP__FROM: noreply@timeld-gateway.local
      TIMELD_GATEWAY_SMTP__AUTH__USER: timeld-gateway
      TIMELD_GATEWAY_SMTP__AUTH__PASS: timeld-gateway
      TIMELD_GATEWAY_ADDRESS__PORT: 8080
      TIMELD_GATEWAY_ADDRESS__HOST: 0.0.0.0
      TIMELD_GATEWAY_ADDRESS__PATH: 
    ports:
      - "8080:8080"
    hostname: timeld-gateway.local
  timeld-cli:
    image: mldio/timeld-cli
    hostname: timeld-cli.local
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # To accept the self-signed cert on the proxy;
    volumes: 
      - ./timeld:/timeld
  mailhog:
    image: mailhog/mailhog
    hostname: mailhog.local
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:587
    ports:
      - "8025:8025"
